Fix for max_frontpage_items
Fortran-FOSS-Programmers/ford pull request #496
Opened 2023-03-27 18:21 UTC by RMShur

- Suppress frontpage section of files/modules/etc if max_frontpage_items=0 (headers were still displayed)
- Fix for not displaying the link to "All files/All modules/etc." below the `max_frontpage_items` items in each category

I haven't run the "Corpus regressions" workflow test on my branch ...

2023-03-28 11:00 UTC, ZedThree requested changes
Thanks for the PR @RMShur, it's much appreciated! I have a few minor comments, but it looks good, cheers!

2023-03-29 10:37 UTC, ZedThree commented on ford/templates/index.html
> +              <ul>
Ok, that's fair enough. We can always change it later and update the tests if we another get opinion in favour of a single list! :smile:

2023-03-29 10:37 UTC, ZedThree approved these changes
Lovely, thanks again @RMShur !

2023-03-29 10:37 UTC, merged

2023-03-29 10:44 UTC, RMShur commented
Ah, I hadn't realized that there actually has been an open issue for this ... thanks!